GET http://localhost:8080/api/guitar
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###
POST http://localhost:8080/api/guitar
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"make": "Taylor","model": "914"}
###

POST http://localhost:8080/api/guitar/inventory?id=2&quantity=4
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

GET http://localhost:8080/api/guitar/inventory?inStock=false
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

POST http://localhost:8080/api/myEndpoint?id3=2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###
GET http://localhost:8080/api/people/10
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

GET http://localhost:8080/api/people
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


###

DELETE http://localhost:8080/api/player
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "nickName": "HoverKan",
  "characterClass": "Lover",
  "level": 10
}
###
